munge key distribution issues

diff --git a/playbooks/roles/munge/tasks/main.yml b/playbooks/roles/munge/tasks/main.yml
--- a/playbooks/roles/munge/tasks/main.yml
+++ b/playbooks/roles/munge/tasks/main.yml
@@ -27,17 +27,6 @@
   register: munge_key_status
   delegate_to: localhost
   become: no
-  when: inventory_hostname == groups['slurm_controllers'][0]
-
-- name: Set munge key status for all nodes
-  ansible.builtin.set_fact:
-    munge_key_status: "{{ munge_key_status.stdout }}"
-  when: inventory_hostname == groups['slurm_controllers'][0]
-
-- name: Set default munge key status for non-controller nodes
-  ansible.builtin.set_fact:
-    munge_key_status: "missing"
-  when: inventory_hostname != groups['slurm_controllers'][0]
 
 - name: Create passwords directory
   ansible.builtin.file:
@@ -46,9 +35,9 @@
     mode: '0700'
   delegate_to: localhost
   become: no
-  when: 
+  when:
     - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status != "encrypted"
+    - munge_key_status.stdout != "encrypted"
 
 - name: Create vault password file if missing
   ansible.builtin.shell: |
@@ -66,79 +55,69 @@
   args:
     creates: /etc/munge/munge.key
   become: yes
-  when: 
+  when:
     - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status != "encrypted"
+    - munge_key_status.stdout != "encrypted"
 
 - name: Set munge key permissions (controller only)
   ansible.builtin.file:
     path: /etc/munge/munge.key
     owner: munge
     group: munge
-    mode: '0400'
+    mode: '0600'
   when: inventory_hostname == groups['slurm_controllers'][0]
 
-- name: Download and encrypt munge key to vault
+- name: Copy unencrypted munge key to temporary location for encryption
   ansible.builtin.fetch:
     src: /etc/munge/munge.key
-    dest: "{{ playbook_dir }}/../passwords/munge.key"
+    dest: /tmp/munge_unencrypted.key
     flat: yes
   become: yes
-  when: 
+  when:
     - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status != "encrypted"
+    - munge_key_status.stdout != "encrypted"
+
+- name: Create MD5 hash of unencrypted munge key for verification
+  ansible.builtin.shell: |
+    md5sum /tmp/munge_unencrypted.key | cut -d' ' -f1 > "{{ playbook_dir }}/../passwords/munge.key.md5"
+  delegate_to: localhost
+  become: no
+  when:
+    - inventory_hostname == groups['slurm_controllers'][0]
+    - munge_key_status.stdout != "encrypted"
 
 - name: Encrypt munge key with ansible-vault
   ansible.builtin.shell: |
-    ansible-vault encrypt "{{ playbook_dir }}/../passwords/munge.key" --vault-password-file "{{ playbook_dir }}/../.vault_pass" || \
-    ansible-vault encrypt "{{ playbook_dir }}/../passwords/munge.key"
+    ansible-vault encrypt /tmp/munge_unencrypted.key --vault-password-file "{{ playbook_dir }}/../.vault_pass" --output "{{ playbook_dir }}/../passwords/munge.key"
   delegate_to: localhost
   become: no
-  when: 
+  when:
     - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status != "encrypted"
+    - munge_key_status.stdout != "encrypted"
 
-- name: Deploy munge key from vault (controller only)
-  ansible.builtin.shell: |
-    ansible-vault decrypt "{{ playbook_dir }}/../passwords/munge.key" --vault-password-file "{{ playbook_dir }}/../.vault_pass" --output /tmp/munge.key
-  delegate_to: localhost
-  become: no
-  when: 
-    - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status == "encrypted"
-
-- name: Copy decrypted munge key to controller
+- name: Deploy munge key from vault to controller
   ansible.builtin.copy:
-    src: /tmp/munge.key
+    src: "{{ playbook_dir }}/../passwords/munge.key"
     dest: /etc/munge/munge.key
     owner: munge
     group: munge
-    mode: '0400'
+    mode: '0600'
   become: yes
-  when: 
+  when:
     - inventory_hostname == groups['slurm_controllers'][0]
-    - munge_key_status == "encrypted"
+    - munge_key_status.stdout == "encrypted"
 
-- name: Copy munge key from vault to all nodes
-  ansible.builtin.shell: |
-    ansible-vault decrypt "{{ playbook_dir }}/../passwords/munge.key" --vault-password-file "{{ playbook_dir }}/../.vault_pass" --output /tmp/munge.key
-  delegate_to: localhost
-  become: no
-  when: 
-    - inventory_hostname != groups['slurm_controllers'][0]
-    - munge_key_status == "encrypted"
-
-- name: Copy decrypted munge key to all nodes
+- name: Deploy munge key from vault to all nodes
   ansible.builtin.copy:
-    src: /tmp/munge.key
+    src: "{{ playbook_dir }}/../passwords/munge.key"
     dest: /etc/munge/munge.key
     owner: munge
     group: munge
-    mode: '0400'
+    mode: '0600'
   become: yes
-  when: 
+  when:
     - inventory_hostname != groups['slurm_controllers'][0]
-    - munge_key_status == "encrypted"
+    - munge_key_status.stdout == "encrypted"
 
 - name: Copy munge key from controller to all nodes (fallback)
   ansible.builtin.copy:
@@ -146,12 +125,46 @@
     dest: /etc/munge/munge.key
     owner: munge
     group: munge
-    mode: '0400'
+    mode: '0600'
     remote_src: yes
-  when: 
-    - inventory_hostname != groups['slurm_controllers'][0]
-    - munge_key_status != "encrypted"
+  when:
+    - munge_key_status.stdout != "encrypted"
   delegate_to: "{{ groups['slurm_controllers'][0] }}"
+
+- name: Create MD5 hash of controller munge key for fallback verification
+  ansible.builtin.shell: |
+    md5sum /etc/munge/munge.key | cut -d' ' -f1 > "{{ playbook_dir }}/../passwords/munge.key.md5"
+  delegate_to: localhost
+  become: no
+  when:
+    - inventory_hostname == groups['slurm_controllers'][0]
+    - munge_key_status.stdout != "encrypted"
+
+- name: Verify munge key MD5 hash on all nodes
+  ansible.builtin.shell: |
+    if [ -f "{{ playbook_dir }}/../passwords/munge.key.md5" ]; then
+      expected_md5=$(cat "{{ playbook_dir }}/../passwords/munge.key.md5")
+      actual_md5=$(md5sum /etc/munge/munge.key | cut -d' ' -f1)
+      if [ "$expected_md5" = "$actual_md5" ]; then
+        echo "Munge key verification PASSED for {{ inventory_hostname }}"
+      else
+        echo "Munge key verification FAILED for {{ inventory_hostname }}: expected $expected_md5, got $actual_md5"
+        exit 1
+      fi
+    else
+      echo "No MD5 hash file found for verification on {{ inventory_hostname }}"
+      exit 1
+    fi
+  register: munge_key_verification
+  failed_when: munge_key_verification.rc != 0
+
+- name: Display munge key verification results
+  ansible.builtin.debug:
+    msg: |
+      Munge Key Verification Results:
+      {% for host in ansible_play_hosts %}
+      {{ host }}: {{ hostvars[host]['munge_key_verification']['stdout'] }}
+      {% endfor %}
 
 - name: Start and enable munge service
   ansible.builtin.systemd:
